[package]
name = "hibernation-control"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
cmd_lib = "1.6.0"
color-eyre = "0.6.2"
envfile = "0.2.1"
eyre = "0.6.8"
libc = "0.2.149"
rust-embed = "8.0.0"
sys-info = "0.9.1"
